  1 set undofile
  2 "Нумерация строк
  3 set number
  4 "Цветовая схема
  5 colorscheme delek
  6 syntax on
  7 "Настройка поиска
  8 set hlsearch
  9 set incsearch
 10 set ignorecase
 11 set smartcase
